# Numpy

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [9]:
# access element in the array 6
a[5]

np.int64(7)

In [10]:
# Change element in the position 
a[3] = 10
a

array([ 1,  2,  3, 10,  5,  7, 12])

In [11]:
# create a range 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# create a range from 3 to 9
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# create an array of size 11 with numbers at equal intervals between 0 and 100
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-dimentional arrays

In [15]:
# create an array with 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
# create an array from a list of lists
n = np.array([
    [1,2,3],
    [4,5,6],
    [8,9,10]
])
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [24]:
# Access element in row 0 and column 1 (Remember arrays are zero-based)
n[0,1]

np.int64(2)

In [25]:
# update element in row 0 and column 1 to 20
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

# Randomly generated arrays

In [29]:
np.random.rand(5, 2)

array([[0.70819005, 0.47237517],
       [0.542122  , 0.06879019],
       [0.61563185, 0.42829291],
       [0.24290704, 0.01557047],
       [0.63066276, 0.23944564]])

In [33]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [34]:
# random normal distribution 

np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
# scalar multiplication by 100
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [39]:
# random integer generation : randint
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operation

In [42]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
# perform an operation on all elements without writing a loop

# multiplication
a * 3

array([ 0,  3,  6,  9, 12])

In [45]:
# addition
a + 3

array([3, 4, 5, 6, 7])

In [48]:
# substraction
a - 3

array([-3, -2, -1,  0,  1])

In [49]:
# division
a / 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [51]:
# chain operation with BODMAS principle
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [53]:
# element-wise sum: a * b, a / b, a - b
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison operations

In [54]:
a

array([0, 1, 2, 3, 4])

In [55]:
# find elements of array 'a' less than or equal 2
a >= 2

array([False, False,  True,  True,  True])

In [56]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [57]:
# find elements of array 'a' greater than elements of array 'b'
a > b

array([False, False,  True,  True,  True])

In [58]:
# create an array with all elements in array 'a' greater than elements in array 'b': positional comparison.
a[a > b]

array([2, 3, 4])

# Summarizing operations

In [59]:
a

array([0, 1, 2, 3, 4])

In [60]:
# return min element in array 'a'
a.min()

np.int64(0)

In [61]:
# return max element in array 'a'
a.max()

np.int64(4)

In [62]:
# compute sum of all element in array 'a'
a.sum()

np.int64(10)

In [63]:
# compute standard deviation of all element in array 'a'
a.std()

np.float64(1.4142135623730951)