# Linear Algebra 

In [18]:
import numpy as np

### Vector addition

In [23]:
u = np.array([1, 0, 0, 2])
u

array([1, 0, 0, 2])

In [24]:
v = np.array([2, 4, 5, 6])
v

array([2, 4, 5, 6])

In [22]:
u + v

array([3, 4, 5, 8])

### Vector multiplication 

In [31]:
# First determine the shapes of the vectors
u_shape = u.shape
v_shape = v.shape

print(f" Vectors u has shape: {u_shape}")
print(f" Vectors v has shape: {v_shape}")

 Vectors u has shape: (4,)
 Vectors v has shape: (4,)


In [38]:
def vector_multiplication(vec1,vec2):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    
    for i in range(n):
        result = result + u[i] + v[i]

    return result

In [39]:
vector_multiplication(u,v)

np.float64(20.0)